### ISSUE TITLE
compile error in Fedora 27 x64

### ISSUE THREAD

**Issue by wheelcomplex** [lwfinger/rtl8812au#3]
Thank you very much for update to support new kernel version.

Linux n550jk.localdomain 4.14.3-300.fc27.x86_64 #1 SMP Mon Dec 4 17:18:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

<pre>
/home/david/sandspace/linux-wifi/rtl8812au/os_dep/mlme_linux.c:396:26: error: expected expression before ‘struct’
  struct sta_info *psta = struct sta_info *psta = (struct sta_info *)FunctionContext;
</pre>

change this line to:
<pre>
  struct sta_info *psta = (struct sta_info *)FunctionContext;
</pre>

and compile passed.

**Comment by lwfinger** [comment]
Sorry about the edit mistake. Have you actually checked the device with kernel 4.15? There is one report that the driver compiled with kernel 4.15, but it did not work. As I have no device, I cannot check operation.

**Comment by wheelcomplex** [comment]
Thanks for https://github.com/lwfinger/rtl8812au/commit/f5d5f97608a7ffc0972fd281728f58bc14870fca

Did not check on 4.15.

Actually, it still does not works in 4.14.3(Fedora 27 x64):

dmesg:
<pre>
[ 2170.712370] usbcore: registered new interface driver rtl8812au
[ 2188.915984] usb 3-2: new high-speed USB device number 10 using xhci_hcd
[ 2189.042465] usb 3-2: New USB device found, idVendor=0bda, idProduct=0811
[ 2189.042468] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2189.042470] usb 3-2: Product: 802.11ac WLAN Adapter 
[ 2189.042471] usb 3-2: Manufacturer: Realtek 
[ 2189.042473] usb 3-2: SerialNumber: 00e04c000001
[ 2189.103630] rtl8812au 3-2:1.0 wlp0s20u2: renamed from wlan0
</pre>

NetworkManager:
<pre>
Dec 16 08:16:06 n550jk.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:16:06 n550jk.localdomain kernel: usb 3-2: new high-speed USB device number 12 using xhci_hcd
Dec 16 08:16:06 n550jk.localdomain kernel: usb 3-2: New USB device found, idVendor=0bda, idProduct=0811
Dec 16 08:16:06 n550jk.localdomain kernel: usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 16 08:16:06 n550jk.localdomain kernel: usb 3-2: Product: 802.11ac WLAN Adapter 
Dec 16 08:16:06 n550jk.localdomain kernel: usb 3-2: Manufacturer: Realtek 
Dec 16 08:16:06 n550jk.localdomain kernel: usb 3-2: SerialNumber: 00e04c000001
Dec 16 08:16:06 n550jk.localdomain systemd[1]: Starting Load/Save RF Kill Switch Status...
Dec 16 08:16:06 n550jk.localdomain NetworkManager[2791]: <info>  [1513365366.7452] wifi-nl80211: (wlan0): using nl80211 for WiFi device control
Dec 16 08:16:06 n550jk.localdomain mtp-probe[25894]: checking bus 3, device 12: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2"
Dec 16 08:16:06 n550jk.localdomain mtp-probe[25894]: bus: 3, device: 12 was not an MTP device
Dec 16 08:16:06 n550jk.localdomain systemd-udevd[25896]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Dec 16 08:16:06 n550jk.localdomain kernel: rtl8812au 3-2:1.0 wlp0s20u2: renamed from wlan0
Dec 16 08:16:06 n550jk.localdomain crda[25902]: setting regulatory domain to NZ based on timezone (Pacific/Auckland)
Dec 16 08:16:06 n550jk.localdomain systemd[1]: Started Load/Save RF Kill Switch Status.
Dec 16 08:16:06 n550jk.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:16:06 n550jk.localdomain NetworkManager[2791]: <info>  [1513365366.7677] rfkill4: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/ieee80211/phy3/rfkill4) (driver rtl8812au)
Dec 16 08:16:09 n550jk.localdomain ModemManager[1957]: <info>  Couldn't check support for device at '/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2': not supported by any plugin
Dec 16 08:16:11 n550jk.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
</pre>

sudo nmcli device (wlp0s20u2 does not showed):
<pre>
DEVICE      TYPE      STATE      CONNECTION  
virbr0      bridge    connected  virbr0      
enp5s0      ethernet  connected  enp5s0      
wlp4s0      wifi      connected  Xiaomi_0800 
lo          loopback  unmanaged  --          
virbr0-nic  tun       unmanaged  --  
</pre>

ifconfig wlp0s20u2
<pre>
wlp0s20u2: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether e8:4e:06:45:1a:b5  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
</pre>

Comparing to a normal usb wifi adapter:

**rtl8812au miss the information after device renamed.**
<pre>
[ 3146.401456] usb 3-2: new high-speed USB device number 13 using xhci_hcd
[ 3146.545489] usb 3-2: New USB device found, idVendor=0411, idProduct=01a2
[ 3146.545493] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3146.545495] usb 3-2: Product: 802.11 n WLAN
[ 3146.545497] usb 3-2: Manufacturer: Ralink
[ 3146.545498] usb 3-2: SerialNumber: 1.0
[ 3146.694691] usb 3-2: reset high-speed USB device number 13 using xhci_hcd
[ 3146.832095] ieee80211 phy4: rt2x00_set_rt: Info - RT chipset 3070, rev 0201 detected
[ 3146.842782] ieee80211 phy4: rt2x00_set_rf: Info - RF chipset 0005 detected
[ 3146.843312] ieee80211 phy4: Selected rate control algorithm 'minstrel_ht'
[ 3146.844681] usbcore: registered new interface driver rt2800usb
[ 3146.856933] rt2800usb 3-2:1.0 wlp0s20u2: renamed from wlan0
[ 3146.876466] IPv6: ADDRCONF(NETDEV_UP): wlp0s20u2: link is not ready
[ 3146.876512] ieee80211 phy4: rt2x00lib_request_firmware: Info - Loading firmware file 'rt2870.bin'
[ 3146.877183] ieee80211 phy4: rt2x00lib_request_firmware: Info - Firmware detected - version: 0.36
[ 3147.052169] IPv6: ADDRCONF(NETDEV_UP): wlp0s20u2: link is not ready
[ 3147.072081] IPv6: ADDRCONF(NETDEV_UP): wlp0s20u2: link is not ready
</pre>

<pre>
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: new high-speed USB device number 13 using xhci_hcd
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: New USB device found, idVendor=0411, idProduct=01a2
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: Product: 802.11 n WLAN
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: Manufacturer: Ralink
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: SerialNumber: 1.0
Dec 16 08:19:40 n550jk.localdomain mtp-probe[28410]: checking bus 3, device 13: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2"
Dec 16 08:19:40 n550jk.localdomain mtp-probe[28410]: bus: 3, device: 13 was not an MTP device
Dec 16 08:19:40 n550jk.localdomain kernel: usb 3-2: reset high-speed USB device number 13 using xhci_hcd
Dec 16 08:19:40 n550jk.localdomain kernel: ieee80211 phy4: rt2x00_set_rt: Info - RT chipset 3070, rev 0201 detected
Dec 16 08:19:40 n550jk.localdomain kernel: ieee80211 phy4: rt2x00_set_rf: Info - RF chipset 0005 detected
Dec 16 08:19:40 n550jk.localdomain kernel: ieee80211 phy4: Selected rate control algorithm 'minstrel_ht'
Dec 16 08:19:40 n550jk.localdomain kernel: usbcore: registered new interface driver rt2800usb
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.5562] wifi-nl80211: (wlan0): using nl80211 for WiFi device control
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.5565] device (wlan0): driver supports Access Point (AP) mode
Dec 16 08:19:40 n550jk.localdomain systemd[1]: Starting Load/Save RF Kill Switch Status...
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.5586] manager: (wlan0): new 802.11 WiFi device (/org/freedesktop/NetworkManager/Devices/6)
Dec 16 08:19:40 n550jk.localdomain systemd-udevd[28409]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Dec 16 08:19:40 n550jk.localdomain kernel: rt2800usb 3-2:1.0 wlp0s20u2: renamed from wlan0
Dec 16 08:19:40 n550jk.localdomain crda[28422]: setting regulatory domain to NZ based on timezone (Pacific/Auckland)
Dec 16 08:19:40 n550jk.localdomain systemd[1]: Started Load/Save RF Kill Switch Status.
Dec 16 08:19:40 n550jk.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.5774] rfkill5: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/ieee80211/phy4/rfkill5) (driver rt2800usb)
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.5815] device (wlan0): interface index 9 renamed iface from 'wlan0' to 'wlp0s20u2'
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.5871] device (wlp0s20u2): state change: unmanaged -> unavailable (reason 'managed', internal state 'external')
Dec 16 08:19:40 n550jk.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): wlp0s20u2: link is not ready
Dec 16 08:19:40 n550jk.localdomain kernel: ieee80211 phy4: rt2x00lib_request_firmware: Info - Loading firmware file 'rt2870.bin'
Dec 16 08:19:40 n550jk.localdomain kernel: ieee80211 phy4: rt2x00lib_request_firmware: Info - Firmware detected - version: 0.36
Dec 16 08:19:40 n550jk.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): wlp0s20u2: link is not ready
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.7820] sup-iface[0x55c0e02ef950,wlp0s20u2]: supports 4 scan SSIDs
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.7827] device (wlp0s20u2): supplicant interface state: starting -> ready
Dec 16 08:19:40 n550jk.localdomain NetworkManager[2791]: <info>  [1513365580.7828] device (wlp0s20u2): state change: unavailable -> disconnected (reason 'supplicant-available', internal state 'managed')
Dec 16 08:19:40 n550jk.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): wlp0s20u2: link is not ready
Dec 16 08:19:41 n550jk.localdomain NetworkManager[2791]: <info>  [1513365581.7241] device (wlp0s20u2): supplicant interface state: ready -> inactive
Dec 16 08:19:43 n550jk.localdomain ModemManager[1957]: <info>  Couldn't check support for device at '/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2': not supported by any plugin

Dec 16 08:19:45 n550jk.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:13 n550jk.localdomain systemd[1]: Starting system activity accounting tool...
Dec 16 08:20:13 n550jk.localdomain systemd[1]: Started system activity accounting tool.
Dec 16 08:20:13 n550jk.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sysstat-collect comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:13 n550jk.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sysstat-collect comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:48 n550jk.localdomain sssd[kcm][24226]: Shutting down
Dec 16 08:20:48 n550jk.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sssd-kcm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:48 n550jk.localdomain sssd[secrets][24227]: Shutting down
Dec 16 08:20:48 n550jk.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sssd-secrets comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:53 n550jk.localdomain systemd[1]: Started SSSD Kerberos Cache Manager.
Dec 16 08:20:53 n550jk.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sssd-kcm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:53 n550jk.localdomain sssd[kcm][29278]: Starting up
Dec 16 08:20:53 n550jk.localdomain systemd[1]: Started SSSD Secrets Service responder.
Dec 16 08:20:53 n550jk.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sssd-secrets comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 16 08:20:53 n550jk.localdomain sssd[secrets][29279]: Starting up

</pre>

**Comment by wheelcomplex** [comment]
FYI:

http://www.szedup.com/support/driver-download/ep-db1607-driver/

http://www.szedup.com/product-item/ac-dual-band-wifi-usb-adapter-2dbi/

** a Realtek 8811au chipset ?**

**Comment by wheelcomplex** [comment]
compile and works on Ubuntu 18.04 x86_64, thanks.
