### ISSUE TITLE
Does not build with GCC 14.1.1

### ISSUE THREAD

**Issue by p0lymesh** [lwfinger/rtl8812au#30]
When I attempt to compile this with **GCC 14.1.1** I immediately get the error output below referencing an incompatible pointer type

`/home/poly/Downloads/rtl8812au/os_dep/ioctl_cfg80211.c:5108:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Wincompatible-pointer-types]
 5108 |         .change_beacon = cfg80211_rtw_change_beacon,
`

**Comment by giuliobenetti** [comment]
@p0lymesh do you mind test my fork mentioned here #32 ? Thanks in advance
