### ISSUE TITLE
does not build with kernel 5.18

### ISSUE THREAD

**Issue by nowhiskey** [lwfinger/rtl8812au#26]
Hello, i am using your sources in for kernels 5.17.xxx but in 5.18 it want build.

This is what i get when running make:

  CC [M]  /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/core/rtw_mp.o
  LD [M]  /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/88XXau.o
ld: /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/core/rtw_security.o: in function `is_multicast_mac_addr':
/home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/include/ieee80211.h:1620: multiple definition of `is_multicast_mac_addr'; /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/core/rtw_cmd.o:/home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/include/ieee80211.h:1620: first defined here
ld: /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/core/rtw_security.o: in function `is_broadcast_mac_addr':
/home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/include/ieee80211.h:1625: multiple definition of `is_broadcast_mac_addr'; /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/core/rtw_cmd.o:/home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/include/ieee80211.h:1625: first defined here
ld: /home/afadoc/Schreibtisch/install/rtl8812au-wifi-stick/core/rtw_security.o: in function `is_zero_mac_addr':

This of course is just a part of the output at the place where it produces an error. the hole output might be too long, but if you want i can provide it to you.

I would be very thankful for any  advice.

Thank you for your work and have a nice day,

Dragan

**Comment by lwfinger** [comment]
That problem was fixed with:

commit c94465bcd02c03f36c0bbfdd7df8785bce682d6a
Author: Larry Finger <Larry.Finger@lwfinger.net>
Date:   Mon Apr 25 11:27:13 2022 -0500

    rtl8812au: Fix build errors with kernel 5.18
    
    Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>

You should do a 'git pull' whenever you get such a problem.

**Comment by nowhiskey** [comment]
Hello, thank you so much for the fast reply. I executed 'git pull' beforehand, and i think  that the problem might have been because i moved the tree to another location in between. I did a bran new 'git clone' and now the driver is compiling very fine.

But with the new kernel5.18 i went into some other troubles with the wifi stick obviously.
When i plug it into the usb slot it seems as if it would not be powered. I can see the device in the Network Manager, but it says there 'device not active'. It still works flawlessly in the 5.17.xx kernel.

I am not sure if the problem is with the driver or with the rest of my system, but for me it looks like the later one.

I'll post here some information from 'dmesg' and 'iwconfig', so if you have any idea where i should look next, i would be very happy!

Here it goes:

This is after a reboot, before the stick is plugged in: 

root@Murija9:/home/afadoc# iwconfig 
lo        no wireless extensions.

enp2s0    no wireless extensions.

root@Murija9:/home/afadoc# ifconfig 
enp2s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 88:a4:c2:dd:f3:8d  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 21  bytes 2327 (2.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21  bytes 2327 (2.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@Murija9:/home/afadoc# 
-------------

Now with the stick plugged into the usb port:

dmesg

[  151.798961] usb 1-4: new high-speed USB device number 3 using xhci_hcd
[  151.953085] usb 1-4: New USB device found, idVendor=2357, idProduct=011e, bcdDevice= 2.00
[  151.953098] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  151.953102] usb 1-4: Product: 802.11ac WLAN Adapter 
[  151.953105] usb 1-4: Manufacturer: Realtek 
[  151.953107] usb 1-4: SerialNumber: 00e04c000001
[  152.702731] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[  152.702950] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[  152.704216] cfg80211: loaded regulatory.db is malformed or signature is missing/invalid
[  152.751883] 8812au: loading out-of-tree module taints kernel.
[  152.752229] 8812au: module verification failed: signature and/or required key missing - tainting kernel
[  153.230720] usbcore: registered new interface driver rtl8812au
[  153.237553] rtl8812au 1-4:1.0 wlx02e04c870000: renamed from wlan1
[  153.263175] rtl8812au 1-4:1.0 wlx00e04c870000: renamed from wlan0


root@Murija9:/home/afadoc# iwconfig 
lo        no wireless extensions.

enp2s0    no wireless extensions.

wlx00e04c870000  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

wlx02e04c870000  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

root@Murija9:/home/afadoc# 

----------
I tried already all the combination of 'ifconfig devicename down' and 'infconfig device up' but still the device is not activated.


Have a good day and very much thanks for your work on this driver!

Dragan
