### ISSUE TITLE
can add kernel 4.15rc1 support?

### ISSUE THREAD

**Issue by oscarbg** [lwfinger/rtl8812au#2]
seems timers were modified and code doesn't compile..

**Comment by lwfinger** [comment]
It took a while, but I just pushed changes that allow building. I think the changes are correct, but I cannot test as I do not have the device.

Please test carefully.

**Comment by oscarbg** [comment]
hi thanks..
will test soon..

**Comment by petehg** [comment]
Have just created the module in opensuse tumbleweed with 4.15-rc2. Insmod won't install it. Modprobe seems to work and lsmod shows the module but the adapter isn't picked up by wicked or networkmanager. I use tumbleweed for "playing with" so I'll go back in later and see if I can pick up some info from dmesg. If you see this and want any more info let me know.

**Comment by lwfinger** [comment]
I need to see some error messages, either from the console where insmod wqon't install it, and from the part of dmesg that shows any errors.

**Comment by petehg** [comment]
I've looked at various things and listed what I think are appropriate system responses:
 from dmesg
[    7.870283] 8812au: loading out-of-tree module taints kernel.
[    7.877422] usbcore: registered new interface driver rtl8812au

from lsmod
usbcore               286720  14 8812au,usbhid,usb_storage,ehci_hcd,ohci_pci,rtl_usb,usblp,xhci_pci,uas,rtl8192cu,rtl8xxxu,ohci_hcd,xhci_hcd,ehci_pci
cfg80211              716800  3 8812au,mac80211,rtlwifi
8812au               1130496  0

from lsusb
Bus 006 Device 003: ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter

from boot.msg
5.013080] usb 6-2: New USB device found, idVendor=0bda, idProduct=a811
<6>[    5.013081] usb 6-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
<6>[    5.013083] usb 6-2: Product: 802.11ac WLAN Adapter 
<6>[    5.013083] usb 6-2: Manufacturer: Realtek 
<6>[    5.013084] usb 6-2: SerialNumber: 00e04c000001

from depmod -av
/lib/modules/4.15.0-rc2-2.gef715eb-default/updates/8812au.ko needs "usb_alloc_urb": /lib/modules/4.15.0-rc2-2.gef715eb-default/kernel/drivers/usb/core/usbcore.ko

from insmod
insmod: ERROR: could not insert module /lib/modules/4.15.0-rc2-2.gef715eb-default/kernel/drivers/net/wireless/8812au.ko: File exists

Hope this helps.

**Comment by lwfinger** [comment]
Not much. The only error listed (insmod) is because the module is already loaded, thus we can ignore that.

I will generate a version that generates lots of extra output. Any change that cannot be tested is difficult. I will post again when the test version is ready.

**Comment by lwfinger** [comment]
OK. The debug codes have been added and pushed. Do another 'git pull', make and 'sudo make install', and then reboot. After the system has been up for about 5 minutes, run the command
'dmesg | grep rtl8812au:'. Post the output.

**Comment by lwfinger** [comment]
If you pulled the latest, the dmesg output had to change. I did a printk everytime a timer was set up, and every time a timer handler routine was entered. The latter messages will start with ""***** rtl8812au: Entered timer handler".

**Comment by petehg** [comment]
I've cleared everything downloaded again and installed. I get exactly the same responses. Everything looks as though it's OK but the adapter is not seen and dmesg gives the same to lines. 
I don't know if your extra code would make much difference to the size but I'm getting an 8812au.ko that's 40MiB. In my main system it's 1.9.
I'm sorry I'm not able to help.

**Comment by lwfinger** [comment]
Strange. My .ko is 1 MB, I.e. less than 1 MiB.

**Comment by lwfinger** [comment]
Additional information: I also revised the code for the rtl8723bu and rtl8188eu repos. Both work on my machine using kernel 4.15.0-rc2.

**Comment by petehg** [comment]
Rtl8192cu works for me in 4.15.0-rc2. And one last point - I installed the 8812au with dkms and the ko is only 2.1MiB now but I'm afraid it still doesn't work and dmesg is still the same. I'll give up on it I think but if you think I can try anything else that might help you just let me know.

**Comment by lwfinger** [comment]
@petehg: If you are in the US and are willing to loan me your rtl8812au, please write me at Larry.Finger@lwfinger.net and I will give you the address to send the device.

**Comment by cki61** [comment]
please have a look at:
https://github.com/mkubecek/vmware-host-modules/commit/562121d7bc06

**Comment by lwfinger** [comment]
I already know how to do it, and I have converted VirtualBox and rtl8188eu. Even so, I have no idea what might be wrong with 8812au.

**Comment by kimocoder** [comment]
Hi there!

I could help out with debugging the kernel v4.15 support..
as for now, this is the output from make:
--------------------------------------------------------------------------------------------------------------------------------
root@kali:~/Downloads/rtl8812au# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.15.0-rc2/build M=/root/Downloads/rtl8812au  modules
make[1]: Entering directory '/root/Downloads/linux-4.15-rc2'
  CC [M]  /root/Downloads/rtl8812au/core/rtw_cmd.o
In file included from /root/Downloads/rtl8812au/include/osdep_service.h:41:0,
                 from /root/Downloads/rtl8812au/include/drv_types.h:32,
                 from /root/Downloads/rtl8812au/core/rtw_cmd.c:22:
/root/Downloads/rtl8812au/include/osdep_service_linux.h: In function ‘_init_timer’:
/root/Downloads/rtl8812au/include/osdep_service_linux.h:254:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/root/Downloads/rtl8812au/include/osdep_service_linux.h:255:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
cc1: some warnings being treated as errors
scripts/Makefile.build:310: recipe for target '/root/Downloads/rtl8812au/core/rtw_cmd.o' failed
make[2]: *** [/root/Downloads/rtl8812au/core/rtw_cmd.o] Error 1
Makefile:1502: recipe for target '_module_/root/Downloads/rtl8812au' failed
make[1]: *** [_module_/root/Downloads/rtl8812au] Error 2
make[1]: Leaving directory '/root/Downloads/linux-4.15-rc2'
Makefile:1052: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by lwfinger** [comment]
Please do another pull and retry. I messed up the repo and redid the 4.15 patch. This version also has been checked to build correctly with 4.14.

**Comment by kimocoder** [comment]
It now compiles fine, great work :)

**Comment by lwfinger** [comment]
The real question is "Does it work?".

**Comment by petehg** [comment]
I've tried it again from scratch. Exactly the same I'm afraid - it's there but not working. In "lsmod | grep 8812" I get some detail but no connection to mac80211 or cfg80211 which show in 4.14.x and with 8192cu in 4.15. I've no idea if this is significant.

**Comment by cki61** [comment]
Yes, it works well on a 4.15.0-rc3-1.g383d72f-default -Kernel!
No problems when compiling, installation and connecting the router by an usb wifi stick..
Thanks a lot for your efforts,
Best Regards!!!

**Comment by lwfinger** [comment]
@petehg: I think you have a user-space problem. Please describe your distro and the method you use to control the network. Please include version numbers for all such network components. The fact that 4.15 works correctly for @cki61 is evidence that my fixes for the 4.15 API changes are correct.

**Comment by petehg** [comment]
I've reverted back to k 4.14 and removed 4.15. I'll install it again when I get the chance and let you know. Otherwise I'm on a standard opensuse tumbleweed with no extra repos but packman and libreoffice.
8812au is working fine for me at the moment with NetworkManager.

**Comment by petehg** [comment]
Ok. I've tried again. I can see the wifi device, I can see the 8812au loaded but they can't see each other.  The systems the tumbleweed mentioned above. 8812au works with k4.14 but not k4.15. It's standard tumbleweed with KDE5 framework 5.40, plasma5 5.11, networkmanager 1.8.4, netcfg 11.5, iproute 2.54.1 and wicked 6.42 but I prefer to use networkmanager.
Is there anything else you would need? I'm using the standard k4.15.0-rc3 from o/s kernel/HEAD repo.

**Comment by kimocoder** [comment]
Confirmed working on kernel v4.15 over here, not just compiling successfully but also working as expected.

**Comment by lwfinger** [comment]
@petehg: Have you told me the USB IDs for your device? If so, I apologize. If not, please send them now.

**Comment by petehg** [comment]
No need for an apology - I'm just happy you do these things for us all. The usb ID is 0bda:a811. I don't actually know the manufacturer but I took the code from an older rtl8812au-master 0x0bda 0xbda811 and I also inserted 0x0bda 0x8812.

**Comment by petehg** [comment]
Sorry that first one should of course read 0x0bda 0xA811

**Comment by oscarbg** [comment]
it works!
